### ISSUE TITLE
Unsure why but since .22 by build fails:

### ISSUE THREAD

**Issue by Kainkainkain** [brandonpittman/gridsome-plugin-tailwindcss#13]
I had some @apply 's not working and so I clumsily uninstalled, installed trying to see if maybe I did something wrong - and now it wont build at all.

Totally removed- will build ok. 
Add this plugin and follow  https://gridsome.org/docs/assets-css/#tailwind
and now I get 
Failed to render /news-story/august
---/node_modules/tailwindcss/tailwind.css:1
(function (exports, require, module, __filename, __dirname) { @tailwind base;

Thought it was the source- so deleted the post and it errored on the next.

**Comment by brandonpittman** [comment]
Just tested it here on a fresh Gridsome app, and it built without issue. Send a link to your repo.

**Comment by Kainkainkain** [comment]
Ok maybe something I've done. I'll report back
