### ISSUE TITLE
Fix `chainWebpack` config minor issues

### ISSUE THREAD

**Issue by hacknug** [brandonpittman/gridsome-plugin-tailwindcss#14]
By default Gridsome comes with `autoprefixer` support. The way we can configure postcss plugins using `chainWebpack` is by touching `options.plugins` which is good enough but far from ideal (because it's somewhat confusing).

What your plugin does is pushing plugins to that array which results in `autoprefixer` running before other postcss plugins. This would effectively break things if it wasn't because `postcss-preset-env` also runs its own version of `autoprefixer`

Ideally you'd unshift all plugins except `purgecss` and push this one while disabling `postcss-preset-env` own instance of `autoprefixer`.

This is how I have it set up on one of my sites:
```js
chainWebpack: (config) => {
  config.module
    .rule('postcss') // css, sass, scss, less, postcss, stylus
    .oneOf('normal') // normal, module
    .use('postcss-loader')
    .tap((options) => {
      options.plugins.unshift(...[
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-preset-env')({
          stage: 0,
          autoprefixer: false,
          features: {
            'nesting-rules': {
              bubble: ['tailwind', 'apply', 'variants', 'responsive', 'screen'],
            },
          },
        }),
      ])

      if (process.env.NODE_ENV === 'production') {
        options.plugins.push(...[
          require('@fullhuman/postcss-purgecss'),
        ])
      }

      return options
    })
},
```

One thing I'm not sure if it's necessary or not is the `features['nesting-rules']` config.

**Comment by brandonpittman** [comment]
Got a long flight coming up Friday, I'll see about this then.

**Comment by brandonpittman** [comment]
[This seems to fix it.](https://github.com/brandonpittman/gridsome-plugin-tailwindcss/commit/87cb15bec03e7f2756d60f898b1608de6cdc3cd7)
