### ISSUE TITLE
Can't turn plugins off

### ISSUE THREAD

**Issue by hacknug** [brandonpittman/gridsome-plugin-tailwindcss#16]
Using `false` for both `shouldImport` and `shouldTimeTravel` doesn't work. This is the error I see:

```bash
Error: false is not a PostCSS plugin
    at Processor.normalize (/project-folder/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/project-folder/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/project-folder/node_modules/postcss/lib/postcss.js:55:10)
    at /project-folder/node_modules/postcss-loader/src/index.js:140:12
    at /project-folder/node_modules/webpack/lib/NormalModule.js:315:20
    at /project-folder/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project-folder/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project-folder/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project-folder/node_modules/postcss-loader/src/index.js:208:9
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brandonpittman** [comment]
I definitely tested this when first making the plugin, must've been something that happened when updating the push/unshift stuff last week.

**Comment by brandonpittman** [comment]
Just ran a test turning off import, preset, and Purge and I didn't have any issues.

```javascript
    {
      use: 'gridsome-plugin-tailwindcss',
      options: {
        shouldImport: false,
        shouldPurge: false,
        shouldTimeTravel: false
      }
    },
```

**Comment by hacknug** [comment]
That's weird, I still see the issue on my project. Could you list your version numbers? Here's mine:
- yarn v1.17.3
- node v12.6.0

```json
{
  "dependencies": {
    "gridsome": "0.7.3"
  },
  "devDependencies": {
    "@tailwindcss/custom-forms": "0.2.1",
    "gridsome-plugin-tailwindcss": "2.2.25",
    "tailwindcss-children": "1.2.0",
    "tailwindcss-interaction-variants": "2.2.0"
  }
}
```

**Comment by brandonpittman** [comment]
❯ npm -v
6.11.3

❯ node -v
v12.6.0

 },
  12   │   "dependencies": {
  13   │     "date-fns": "^2.2.1",
  14   │     "gridsome": "^0.7.3"
  15   │   },
  16   │   "devDependencies": {
  17   │     "@babel/plugin-proposal-class-properties": "^7.5.5",
  18   │     "@babel/plugin-transform-object-assign": "^7.2.0",
  19   │     "@gridsome/plugin-critical": "^0.1.5",
  20   │     "@gridsome/remark-prismjs": "0.2.0",
  21   │     "@gridsome/source-filesystem": "^0.6.0",
  22   │     "@gridsome/transformer-remark": "^0.3.3",
  23   │     "@vue/cli-service": "^3.11.0",
  24   │     "eslint": "^6.4.0",
  25   │     "eslint-config-xo": "^0.26.0",
  26   │     "eslint-plugin-gridsome": "^1.3.0",
  27   │     "eslint-plugin-vue": "^5.2.3",
  28   │     "gridsome-plugin-base-components": "latest",
  29   │     "gridsome-plugin-rss": "^1.1.3",
  30   │     "gridsome-plugin-tailwindcss": "latest",
  31   │     "netlify-lambda": "^1.6.3",
  32   │     "stylelint-config-recommended": "^3.0.0",
  33   │     "stylelint-config-standard": "^19.0.0",
  34   │     "svg-to-vue-component": "^0.3.8",
  35   │     "tailwindcss-plugin-fancy": "latest",
  36   │     "xo": "^0.24.0"
  37   │   }

**Comment by matthewmorek** [comment]
I'm having the exact same issue, even when following the above config templates. This fails both local and remote `gridsome build` on Netlify.

```
Gridsome v0.7.13

Initializing plugins...
Load sources - 0.6s
Create GraphQL schema - 0.04s
Create pages and templates - 0.02s
Generate temporary code - 0.02s
Bootstrap finish - 1.43s
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: false is not a PostCSS plugin
    at Processor.normalize (/Users/mmorek/Projects/airsoft-directory/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/mmorek/Projects/airsoft-directory/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/mmorek/Projects/airsoft-directory/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/mmorek/Projects/airsoft-directory/node_modules/postcss-loader/src/index.js:140:12
    at /Users/mmorek/Projects/airsoft-directory/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/mmorek/Projects/airsoft-directory/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/mmorek/Projects/airsoft-directory/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/mmorek/Projects/airsoft-directory/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mmorek/Projects/airsoft-directory/node_modules/postcss-loader/src/index.js:208:9
```

`gridsome.config.js`
```
module.exports = {
  siteName: "ActionHub",
  plugins: [
    {
      use: "gridsome-plugin-tailwindcss",
      options: {
        shouldImport: false,
        shouldPurge: false,
        shouldTimeTravel: false
      }
    }
  ]
};
```

npm: `6.13.7`
Node: `v12.14.0`

Dependencies:
```
"dependencies": {
  "@tailwindcss/ui": "^0.1.3",
  "gridsome": "^0.7.0",
  "gridsome-plugin-tailwindcss": "^2.2.36"
}
```

**Comment by brandonpittman** [comment]
Well, 💩.

Pushing 2.2.38 now to fix this.
