### ISSUE TITLE
@screen and @apply not working  for <style lang="postcss">

### ISSUE THREAD

**Issue by robinscholz** [brandonpittman/gridsome-plugin-tailwindcss#17]
When applying a language definition to the style block of a `.vue` component, `@screen` and `@apply` stop working. Both in development and production builds.

```
<style lang="postcss">
.vh__title h1:after,
.vh__title h2:after {
  display: none;
}

@screen md {
  .video-header {
    height: 560px;
  }
}

</style>
```

When removing the `lang="postcss"` defintion they get converted fine.
When changing the following line from `css` to `postcss` it also works:
Changing https://github.com/brandonpittman/gridsome-plugin-tailwindcss/blob/71f7f342cf2df2b82a8c99e4c82ace6622479005/gridsome.server.js#L23

Consequently changing `gridsome.server.js` fixes the issue:

```
const languages = ['css', 'postcss']

  api.chainWebpack(config => {
    languages.forEach(language => {
      config.module
        .rule(language)
        .oneOf("normal")
        .use("postcss-loader")
        .tap(options => {
          options.plugins.unshift(
            ...[
              shouldImport && postcssImport,
              tailwind,
              shouldTimeTravel && postcssPresetEnv
            ]
          );

          process.env.NODE_ENV === "production" &&
            shouldPurge &&
            options.plugins.push(purgecss);

          return options;
        });
    });
  });
```

I'd be happy to supply a pull request, if you think the solution is robust enough.

**Comment by brandonpittman** [comment]
It's a feature.
