### ISSUE TITLE
@apply not working with tailwind components

### ISSUE THREAD

**Issue by sanscheese** [brandonpittman/gridsome-plugin-tailwindcss#19]
Still looking into this issue, but think is something that should be working.

If I create a Tailwind component: https://tailwindcss.com/docs/plugins/#adding-components

I can't use it in `@apply` statements in my Gridsome app. (I can change them to work of `addUtilities`, so makes me think is an issue with this setup)

As an example I'm looking to be able to do a statement like this in my .vue components:

```css
.my-component >>> a {
  @apply btn;
}
```

**Comment by brandonpittman** [comment]
Give me a repo.

**Comment by hacknug** [comment]
Did you set `lang="postcss"` on your `style` tag?

**Comment by brandonpittman** [comment]
@hacknug @sanscheese I've been using this plugin for months, with `@apply` in components, with both `lang="postcss"` and no `lang` set, and the `@apply`s work.

**Comment by sanscheese** [comment]
I've set up a demo:
https://codesandbox.io/s/gridsomegridsome-starter-default-u09ub

Can see the plugin in `tailwind.config.js` and `@apply` in `src/pages/index.vue`. Changing the plugin to use `addUtilities` instead of `addComponents` will work, but this isn't shouldn't be a utility.

* This is a fairly edge case issue. `@apply` is working for standard tailwind classes throughout the build. I'm still not sure if this is a limit with postcss `@apply`. I'm pretty sure I had it working in a vue-cli project.

**Comment by hacknug** [comment]
Seems like core only handles `@apply` for utilities and this line is the culprit: https://github.com/tailwindcss/tailwindcss/blob/master/src/processTailwindFeatures.js#L25

**Comment by brandonpittman** [comment]
@sanscheese You use @apply to apply utilities, not components.

https://tailwindcss.com/docs/functions-and-directives/#apply

Read the docs.

**Comment by sanscheese** [comment]
Right indeed. Sorry for the bother!
