### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by EryouHao** [brandonpittman/gridsome-plugin-tailwindcss#2]
Thanks for your work. but I use it not work in gridsome, can you write a demo?

**Comment by typerory** [comment]
@EryouHao I will be working on Gridsome/Tailwind this week. If you'd like I could put together a quick video (unpolished production).

**Comment by brandonpittman** [comment]
> Thanks for your work. but I use it not work in gridsome, can you write a demo?

More info is always welcome.

**Comment by typerory** [comment]
I'll put together a quick screencast with a basic Gatsby starter. Then I'll add your Tailwind and PostCSS packages. Hopefully, I get it all to work. Ha.

**Comment by typerory** [comment]
Hey Brandon I tried the method you posted on your blog as an alternative to this but no luck.  I'm not seeing any effect when using tailwind classes. I could use your help.

**Comment by brandonpittman** [comment]
@typerory It works.

https://github.com/brandonpittman/gridsome-plugin-tailwindcss-ffs
