### ISSUE TITLE
How to add whitelist patter for purgecss?

### ISSUE THREAD

**Issue by popcornkiller1088** [brandonpittman/gridsome-plugin-tailwindcss#20]
How do I add purgecss options to this plugin ? example for vue transition, I would like to do some whitelist on purgecss:
`
      whitelistPatterns: [
        /-enter-active$/,
        /-leave-active$/,
        /-enter$/,
        /-leave-to$/
      ],
`

**Comment by brandonpittman** [comment]
Pass it in to `options.purgeConfig`.
