### ISSUE TITLE
gridsome.client.js missing from npm package in 2.2.28

### ISSUE THREAD

**Issue by Nocory** [brandonpittman/gridsome-plugin-tailwindcss#23]
I just set up a new project and noticed that the plugin currently seems to be broken due to `gridsome.client.js` missing from version 2.2.28 of the npm release.

2.2.27 still includes the file and runs normally.

**Comment by brandonpittman** [comment]
I'm sorry about that. The `files` key in `package.json` had `gridsome.config.js` listed instead of `gridsome.client.js`. It's fixed now.
