### ISSUE TITLE
Tailwind Canary

### ISSUE THREAD

**Issue by derevandal** [brandonpittman/gridsome-plugin-tailwindcss#25]
Hi!

I'm using this plugin on production with some plugins. And when you released a version with tailwind canary, all my pipeline was broken because of the new features added in release candidate version.

Could you mantain a stable version of tailwind?

I'm using v2.2.26.

Thanks.

**Comment by brandonpittman** [comment]
What broke?

**Comment by brandonpittman** [comment]
No response for a week. Closing.
