### ISSUE TITLE
Need ability to run autoprefixer

### ISSUE THREAD

**Issue by Devportobello** [brandonpittman/gridsome-plugin-tailwindcss#3]
Hi,

When using your plugin, autoprefixer did not run

For information about old way to add tailwind to gridsome with autoprefixer :  https://github.com/gridsome/gridsome/issues/9#issuecomment-455592474

**Comment by brandonpittman** [comment]
@Devportobello https://www.brandonpittman.net/tailwind-purge-config

**Comment by brandonpittman** [comment]
Done.
