### ISSUE TITLE
Build without tailwind

### ISSUE THREAD

**Issue by cravacuore** [brandonpittman/gridsome-plugin-tailwindcss#37]
Hi,

I'm trying to have a build of a site using this plugin, locally when doing `gridsome develop` I don't have any problems, but when generating a build with `gridsome build` I am not able to have a site with applied styles.

I even tried by simply cloning the example site https://github.com/brandonpittman/gridsome-plugin-tailwindcss-ffs. And doing:

npm install
gridsome develop (works fine):
![Screenshot_20200323_142207](https://user-images.githubusercontent.com/4295345/77344115-79968280-6d11-11ea-850a-cbc0432922a5.png)
gridsome build (generates this page with no styles):
![Screenshot_20200323_142118](https://user-images.githubusercontent.com/4295345/77344146-83b88100-6d11-11ea-9262-ccd9d651f975.png)

If someone could please guide me in what I could be doing wrong I'll appreciate. Thanks.

**Comment by brandonpittman** [comment]
`npx serve dist` works just fine. I'd also guarantee you're trying to just open up `index.html` in a browser without running a web serve—which won't work.

**Comment by webmasterowi** [comment]
I'm facing the same issue, i try to upload to netlify and is not working, i get the html but without not style

**Comment by brandonpittman** [comment]
@webmasterowi Share your code if you want help.
