### ISSUE TITLE
Is it a way to access options within the tailwind.js file from vue SFC?

### ISSUE THREAD

**Issue by htasha** [brandonpittman/gridsome-plugin-tailwindcss#4]
I wanted to access the colors object in `tailwind.js` from vue SFC in order to apply changes to css variables base on component props.

I could just declare these variables in a global css file and assign the colors manually, but what's the point then of having them stored in `tailwind.js` besides of generating class utilities?

Probably there is a better way of doing this but I would like to do something like this:

```
props: {
    color: {
      type: String
    }
  },
computed: {
    style() {
      return {
        "--card-color": this.$tailwind.colors[this.color]
      };
    }
  }

.card {
  --card-color: white;
  background-color: var(--card-color);
}
```

**Comment by hacknug** [comment]
Why not use Tailwind's [`config()`](https://tailwindcss.com/docs/functions-and-directives#config)?

**Comment by htasha** [comment]
Where? In the javascript? It will undefined. You can't assign `config` to a css variable it doesn't compute to a color

**Comment by hacknug** [comment]
On your (Post)CSS:

```pcss
.card {
  background-color: config(colors.nameOfYourColor);
}
```

**Comment by htasha** [comment]
I know but you can't change it dinamically from javascript. Somebody mention to add the object colors to Vue prototype, thanks anyway, i think I'll do that

**Comment by hacknug** [comment]
Ahhhhh. I misunderstood the question. Sorry 😅

**Comment by flofleche** [comment]
Hi there I know this post is closed but I think this might still be useful to mention as I struggled myself to find the information in the TailwindCSS doc :
https://tailwindcss.com/docs/configuration/#referencing-in-javascript

Cheers and I hope you don't see this comment as a noise on this backlog..?
