### ISSUE TITLE
Girdsome develop breaks due to fs dendency

### ISSUE THREAD

**Issue by djclarkson** [brandonpittman/gridsome-plugin-tailwindcss#5]
I get a dependency error with fs

```
ERROR  Failed to compile with 6 errors                                                                                                                                                                 
This dependency was not found:
fs in ./node_modules/file-system/file-system.js, ./node_modules/fs.realpath/old.js and 4 others
To install it, you can run: npm install --save fs`
```

Have seen some issues in other projects where the fix was a webpack config as such:

```
var config = {
    node: {
        fs: "empty"
    }
}
```
I wanted to test, but there's no webpack config file.

**Comment by brandonpittman** [comment]
Try install `fs`. Just created a fresh gridsome project, added the plugin, and it worked fine.

**Comment by djclarkson** [comment]
I tried installed fs via npm. 

```
npm install --save fs
+ fs@0.0.1-security
added 1 package, removed 7 packages and audited 14039 packages in 8.265s
```
The fs npm is a security [holding package](https://www.npmjs.com/package/fs
). So in my case, npm install --save fs still results in a failure. I tried installing fs-extra, that also didn't work.

**Comment by cossssmin** [comment]
I think the package in question is this one:

https://www.npmjs.com/package/file-system
