### ISSUE TITLE
whitelisting custom classes not working

### ISSUE THREAD

**Issue by brianshano** [brandonpittman/gridsome-plugin-tailwindcss#54]
I've tried a few different ways to whitelist some classes but they're excluded every time I build my gridsome app. Local dev version working fine. 

They're for a 3rd party library, abcjs, which is working well but without styles. It is rendered in dom after page load hence why the css is being purged, so I assume whitelisting it will include it. 

My config:
```
{
      use: 'gridsome-plugin-tailwindcss',
      options: {
        // tailwindConfig: '',
        purgeConfig: {
          whitelistPatterns: [/abcjs/],
          whitelistPatternsChildren: [/abcjs/],
        },
        // presetEnvConfig: {},
        shouldPurge: true
        shouldImport: true,
        shouldTimeTravel: true,
      },
},
```

Should I expect this to work or am I whitelisting in the wrong place?

**Comment by brandonpittman** [comment]
Can I see the repo?

**Comment by brianshano** [comment]
> Can I see the repo?

Sure https://github.com/brianshano/tunesource-gridsome

**Comment by levirs565** [comment]
You can use comment to whitelist css clasess:

```css
/* purgecss start ignore */
h1 {
  color: blue
}
/* purgecss end ignore */
```

The `h1` style will be ignore and whitelisted

**Comment by brandonpittman** [comment]
@brianshano Is the HTML you’re accessing in a nested component?

**Comment by brianshano** [comment]
Thanks @levirs565 ignore comments were just what I needed. 
Yes HTML is in a nested component

**Comment by brandonpittman** [comment]
@brianshano Go look at the deep selector docs in the Vue-loader documentation.
