### ISSUE TITLE
Added base styles get purged if unused

### ISSUE THREAD

**Issue by mario-neuhold** [brandonpittman/gridsome-plugin-tailwindcss#58]
Not sure if I'm getting this right or if I'm missing something important here.

I'm adding some base styles like described in the [tailwind docs](https://tailwindcss.com/docs/plugins/#adding-base-styles):
```javascript
// tailwind.config.js
const plugin = require('tailwindcss/plugin')

module.exports = {
  plugins: [
    plugin(function({ addBase, config }) {
      addBase({
        '.class1': { fontSize: config('theme.fontSize.2xl') },
        '.class2': { fontSize: config('theme.fontSize.xl') },
        '.class3': { fontSize: config('theme.fontSize.lg') },
      })
    })
  ]
}
```

But these styles get purged in production when they are not used in any template file (coming from an external cms in my case).

According to the [tailwind docs](https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss-manually) it is recommended to only purge utility classes, not base and component classes by importing the tailwind styles like this:
```css
/* purgecss start ignore */
@tailwind base;
@tailwind components;
/* purgecss end ignore */

@tailwind utilities;
```

Don't we need a local `./tailwind.css` in this plugin with these comments that we import instead of the original `/tailwindcss/tailwind.css`?
If this makes sense I'd happily provide a PR for it.

Note: I actually had to use important comments like `/*! purgecss start ignore */` to make it work

**Comment by brandonpittman** [comment]
@mario-neuhold Considering the way Tailwind has moved with doing the purging on its own, I'm not sure how necessary this plugin is now.

**Comment by brandonpittman** [comment]
@mario-neuhold You can whitelist any styles that you're afraid will get purged.  A blanket `ignore` block isn't the only way to ensure styles don't get purged. Or...don't use the purge feature of this plugin, and set up PurgeCSS using Tailwind 1.4's new way of doing purge in the config file.

**Comment by mario-neuhold** [comment]
I see, thanks for the really fast answer. I haven't used PurgeCSS or even Tailwind before, so it was a bit confusing to begin with.
