### ISSUE TITLE
[RFC] Remove PurgeCSS in v3

### ISSUE THREAD

**Issue by brandonpittman** [brandonpittman/gridsome-plugin-tailwindcss#59]
Now that Tailwind 1.4+ has PurgeCSS built-in, it doesn't make much sense to have it in this plugin, and it makes customizing Tailwind's built-in Purge a pain in the ass.

## Proposed Changes

- Remove PurgeCSS
- On install, if `tailwind.config.js` doesn't exist, create one with sensible PurgeCSS defaults for Gridsome.

**Comment by maxerbox** [comment]
While waiting for the new release, here is a workaround to use tailwind purge css
Inside your tailwind config:
```js
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'src/components/**/*.vue',
      'src/layouts/**/*.vue',
      'src/pages/**/*.vue',
      'gridsome.config.js',
    ],
  },
```
And set the shouldPurge plugin option to false.
It will also disable those tailwind warning when you build

**Comment by brandonpittman** [comment]
Closed with https://github.com/brandonpittman/gridsome-plugin-tailwindcss/commit/38ca21e074390fa6751f211b149c887f4476983b
