### ISSUE TITLE
[RFC] Stop direct import of tailwind.css from Tailwind NPM package

### ISSUE THREAD

**Issue by brandonpittman** [brandonpittman/gridsome-plugin-tailwindcss#60]
Nothing has been the cause of more questions than "Where do I put my CSS file?!?!" So, for v3, let's just go back to having a CSS file in the assets directory, and stop directly importing one.

## Proposed Changes

- On install, create a `tailwind.css` file in `/src/assets/css` if one doesn't already exist, pre-populated with the standard Tailwind directives.

**Comment by webmasterowi** [comment]
That is really good, any idea when this update will come out?

**Comment by abhishekashyap** [comment]
Any updates?

**Comment by brandonpittman** [comment]
@abhishekashyap I closed this because even @adamwathan endorsed (which made me stop caring about the 3 people who ever complained about this).

**Comment by abhishekashyap** [comment]
But sometimes it is needed to import **custom CSS** as mentioned by @adamwathan along with TailwindCSS, like while implementing Dark mode using CSS variables.

**Comment by brandonpittman** [comment]
@abhishekashyap Use `tailwind.config.js`.
