### ISSUE TITLE
Just to confirm..  We don't need to import Tailwind files?

### ISSUE THREAD

**Issue by rylanharper** [brandonpittman/gridsome-plugin-tailwindcss#61]
Hello! 👋 Thank you for this plugin here. This probably has been answered a million times, but the grammar on the docs are a bit confusing on this line 👉[here](https://github.com/brandonpittman/gridsome-plugin-tailwindcss/blob/master/README.md#L22). 

Did you mean to say "It's just a css file that includes..." or did you mean "Add a css files that includes..."? In my Dev environment and the starters within the Readme there are no css folders/tailwind imports and tailwind seems to be working fine without them. However, while looking at other gridsome/tailwind starters, I see people have included a css folder with the tailwind imports. I just wanted to confirm which one it is 🙃

**Comment by rylanharper** [comment]
So yes or no?

**Comment by brandonpittman** [comment]
@rylanharper Nope.

**Comment by rylanharper** [comment]
Okay great! Haha that’s what I thought too.. a lot of extra css there for no reason 😅

Thank you I just wanted to confirm that before I got started on a little project I’m working on 😁

**Comment by hongweitang** [comment]
That explains why I had double normalize.css files in my browser inspector.
