### ISSUE TITLE
Adding local fonts to stylesheet renders them at bottom of CSS file

### ISSUE THREAD

**Issue by onebrightlight** [brandonpittman/gridsome-plugin-tailwindcss#64]
I might be missing something in the process, but I’m trying to add a custom local font (Manrope) to my CSS, but the Tailwind plugin seems to always make sure it is at the top of the CSS file, so anything I declare in `Default.vue` ends up rendering at the bottom of the CSS file, causing my `@font` declaration to not show up early enough for my naming it in `tailwind.config.js`.

Is there a way to pass this into the process that I’m missing? I normally work with Tailwind with PostCSS in Laravel Mix, so this is my first attempt at trying it in an SSG.

Thanks for any help!

**Comment by brandonpittman** [comment]
@onebrightlight Pretty sure that Vue always injects their stuff last. Try declaring your font in `tailwind.config.js`.
