### ISSUE TITLE
VSCode TailwindCSS Addons Require tailwind.config.js to work

### ISSUE THREAD

**Issue by brandiqa** [brandonpittman/gridsome-plugin-tailwindcss#65]
Thanks @brandonpittman for building the plugin.

Kindly add a note in the documentation that the VSCode addons:

- [TailwindCSS Intellisense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)
- [Headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind)

...require `tailwind.config.js` within the project folder to be present in order for them to work. After generating the config file using the command `./node_modules/.bin/tailwind init` to generate the file, VSCode needs to be restarted in order for the plugins to function.

**Comment by brandonpittman** [comment]
@brandiqa vim 4 life.
