### ISSUE TITLE
Question: built in purge

### ISSUE THREAD

**Issue by vitalikda** [brandonpittman/gridsome-plugin-tailwindcss#66]
Plugin doesn't enable Tailwind CSS purge function by default. I had to add config file to enable it (below). Is it a correct behavior? 

```js
module.exports = {
  future: {
    purgeLayersByDefault: true,
  },
  purge: ['./src/**/*.html', './src/**/*.vue', './src/**/*.jsx'],
  theme: {},
  variants: {},
  plugins: [],
};
```

Also, I enabled the new `layers` mode to hide warning - https://tailwindcss.com/docs/upcoming-changes

```
warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
```

_Brandon, thanks for the great plugin._

**Comment by TeNNoX** [comment]
@brandonpittman I also have this question - what's the reason that you closed it?

**Comment by brandonpittman** [comment]
It’s not an issue.
