### ISSUE TITLE
Preset env no longer working in .css files?

### ISSUE THREAD

**Issue by lynden-jones** [brandonpittman/gridsome-plugin-tailwindcss#67]
When I upgraded this package from the previous release, it seems that preset env no longer works in my .css files.

Specifically I have nested rules like this, the hover rule works when in my .vue files but not when in my .css files.  

```
.box-link {
  background-color: red;
  &:hover {
    background-color: blue;
    }
}
```

Is this intended behavior or did I miss something?

I have this in my gridsome config:

```
{
      use: 'gridsome-plugin-tailwindcss',
      options: {
        tailwindConfig: 'tailwind.config.js',
        presetEnvConfig: { stage: 0 },
        shouldImport: true,
        shouldTimeTravel: true
      }
    },
```

**Comment by brandonpittman** [comment]
Share a repo and I’ll look at it.

**Comment by lynden-jones** [comment]
My bad, seems to be a purgeCss problem.
