### ISSUE TITLE
TailwindCSS 2 Support

### ISSUE THREAD

**Issue by thinkflo** [brandonpittman/gridsome-plugin-tailwindcss#68]
A bit of dependancy inception but TailwindCSS 2.0+ depends on `PostCSS 8`.  Where this (otherwise amazing) Gridsome plugin depends on `postcss-import-url`, which is presently NOT PostCSS8 compatible, and cannot switch to TailwindCSS 2. 

In looking at `postcss-import-url`, this module is sporadically maintained.   Would it be possible to fork it to provide the functionality needed for this plugin so that we can migrate to PostCSS 8, and thus migrate to TailwindCSS 2.0?

**Comment by brandonpittman** [comment]
Should drop support for the URL plugin TBH.

**Comment by brandonpittman** [comment]
@thinkflo does the compat build work?

**Comment by scrambldchannel** [comment]
I have what I assume is a related issue. I get `Error: PostCSS plugin tailwindcss requires PostCSS 8.` when trying to run `gridsome develop` today after installing the plugin in a newly created site.

I am a bit clueless about managing node packages, how can I force gridsome-plugin-tailwindcss use an older version of tailwind? I tried installing the compatibility build mentioned [here](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) but that didn't seem to affect the version the plugin was using. Any help much appreciated!

Cheers
Alex

**Comment by brandonpittman** [comment]
https://github.com/brandonpittman/gridsome-plugin-tailwindcss/releases/edit/untagged-60868df1c7d3c0fc9d97 should sort this out.

All deps are now peer deps.

**Comment by sergeyfilimonov** [comment]
@brandonpittman sorry but in the end what's the proper way to use 2.0 now? Is there a working example?

**Comment by brandonpittman** [comment]
@sergeyfilimonov Are the instructions in the README not working?

**Comment by sergeyfilimonov** [comment]
@brandonpittman nope:
<img width="1648" alt="Снимок экрана 2020-11-30 в 15 38 33" src="https://user-images.githubusercontent.com/43918077/100611253-1dfda980-3322-11eb-9120-39b30992241c.png">

**Comment by brandonpittman** [comment]
@sergeyfilimonov That's probably Gridsome's fault. [Try the Tailwind 2 compat version. ](https://tailwindcss.com/docs/upgrading-to-v2#install-tailwind-css-v2-0-and-post-css-8)

**Comment by sergeyfilimonov** [comment]
@brandonpittman thanks! It helped but the instructions of Tailwind lack information on `postcss-import`. One should not install v.13, it should be `yarn add postcss-import@^12`. Otherwise when `shouldImport` is set to `true` you'll get an error about PostCSS 8 as well.

**Comment by brandonpittman** [comment]
@sergeyfilimonov Big reason why I turned off the plugins by default. I don't use any other PostCSS plugins either. I'd recommend organizing your code so that you don't need `@import`. I also haven't used `@apply` in a year either. I really wish I had just pulled out the `shouldImport` and `shouldTimeTravel` configs.

**Comment by sergeyfilimonov** [comment]
@brandonpittman what if you want to create some global classes like .h1, .h2, .h3 — where would you put this? In the main Layout? Or if you need to create some animations which often have tens of lines of code. This all needs to be put in separate files which have to be imported.

**Comment by thinkflo** [comment]
Yeah, I'm in a similar boat.  Too many PostCSS errors.  The 7 compat version doesn't help.  And I need to be able to use @apply since there is inline HTM I am rendering in Gridsome templates that come from a WYSIWYG editor in a CMS. So I don't have a way to decorate the elements with tailwind classes so I @apply them using selectors.  Losing this ability is a dealbreaker.

**Comment by sergeyfilimonov** [comment]
@thinkflo check this https://tailwindcss.com/docs/installation#post-css-7-compatibility-build and my reply https://github.com/brandonpittman/gridsome-plugin-tailwindcss/issues/68#issuecomment-735773442 — it works fine for me now with these versions.

**Comment by thinkflo** [comment]
Will try.  Thanks!

**Comment by Sergix** [comment]
So this won't resolve until `postcss-import-url` updates? It'll be a while, looking at that package's changelog... I agree with @brandonpittman, that package should probably be dropped or at least forked for the time being. Should I file a compatibility issue on the Gridsome repo?

**Comment by brandonpittman** [comment]
@Sergix fork it if you want.

**Comment by iamarpitpatidar** [comment]
@brandonpittman  I am not sure but if I am not using `shouldImport` and `shouldTimeTravel` then the plugin should work right?
