### ISSUE TITLE
Version bump to 2.0 after adding Tailwind 1.0 support

### ISSUE THREAD

**Issue by gilesbutler** [brandonpittman/gridsome-plugin-tailwindcss#7]
Hey @brandonpittman,

Introducing support for Tailwind 1.0 is a breaking change and the package should probably be bumped to `2.0.0`. 

We have `"gridsome-plugin-tailwindcss": "^1.0.6"` in our package.json and when our build system (Netlify) get's the packages it pulls in the latest version `1.3.2` which breaks because the config is completely different. We've locked the package to `1.0.6` now but it took an hour to figure out what was going on as there's no clear error explaining what has happened. Also [this issue](https://github.com/brandonpittman/gridsome-plugin-tailwindcss/issues/6) really didn't help as we assumed this plugin hadn't updated to 1.0.

Anyway just posting this here to hopefully help other people and appreciate you maintaining the plugin 👍

**Comment by brandonpittman** [comment]
Thanks. Should've paid more attention to semver. It's been bumped to 2.0.0.

**Comment by gilesbutler** [comment]
Nice one, thanks @brandonpittman
