### ISSUE TITLE
Missing utils classes

### ISSUE THREAD

**Issue by kwiat1990** [brandonpittman/gridsome-plugin-tailwindcss#70]
Hi,

I'm am using this plugin from some time already and today I noticed that some of Tailwind's classes that are listed in the official Docs are not present by me at all.

For example:
* for both margin and padding starting from `m-7` and `p-7` there are no classes with odd numbers),
* font-size classes are missing from `text-7xl`

Is this a thing of plugin's internal config or is rather something broken?

My entire config looks like this:
```
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  purge: [],
  theme: {
    colors: {
      primary: "var(--color-primary)",
      secondary: "var(--color-secondary)",
      "surface-primary": "var(--bg-primary)",
      "surface-secondary": "var(--bg-secondary)",
      "accent-primary": "var(--accent-primary)",
      "accent-secondary": "var(--accent-secondary)"
    },
    container: {
      center: true,
      padding: defaultTheme.spacing["4"],
    },
    typography: {
      default: {
        css: {
          color: "inherit",
          maxWidth: "none"
        }
      }
    },
    extend: {
      rotate: {
        135: "135deg",
        270: "270deg",
      },
    },
  },
  variants: {
    margin: ["odd", "even"],
  },
  plugins: [require("@tailwindcss/typography")],
};
```

**Comment by brandonpittman** [comment]
Upgrade Tailwind

**Comment by brandonpittman** [comment]
Package.json?

**Comment by kwiat1990** [comment]
Here it is:
```
{
  "main": "gridsome.config.js",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/source-strapi": "^0.2.0",
    "gridsome": "^0.7.0"
  },
  "devDependencies": {
    "eslint": "^7.12.1",
    "node-sass": "^5.0.0",
    "prettier": "2.1.2",
    "sass-loader": "^10.0.5"
  }
}
```

**Comment by brandonpittman** [comment]
Try installing Tailwind

**Comment by kwiat1990** [comment]
> Try installing Tailwind

Please, take another look, I missed the plugin itself. It was correctly installed by npm and like I sad - Tailwind works but some classes simply don't exist.

**Comment by dsturm** [comment]
Hi @kwiat1990,

did you try it with the current version '^4.1.0'?

**Comment by kwiat1990** [comment]
Yeah, it turned out to be just a problem with old versions. After upgrading it works all seamless.
@dsturm thanks for the tipp to update my packages.
