### ISSUE TITLE
Best way to add postcss-nested?

### ISSUE THREAD

**Issue by sergeyfilimonov** [brandonpittman/gridsome-plugin-tailwindcss#71]
What's the best way to add `postcss-nested`? It's not possible via options so I added the following code to `gruesome.config.js`:

```js
config.module
      .rule('css')
      .oneOf('normal')
      .use('postcss-loader')
      .tap(options => {
        options.plugins.unshift(...[
          require('postcss-import'),
          require('postcss-nested'),
          require('tailwindcss'),
        ])
        return options
      })
```

It's working but it's confusing as it seems I add `tailwindcss` twice — by the plugin gridsome-plugin-tailwindcss and here. Is it correct?

**Comment by brandonpittman** [comment]
If you’re at this point, you should just use Tailwind without this plugin.
