### ISSUE TITLE
@screen function not printing correctly in develop mode

### ISSUE THREAD

**Issue by tanc** [brandonpittman/gridsome-plugin-tailwindcss#8]
Not 100% certain where the issue lies but it seems that Tailwind's @screen function is printing correctly only when running `gridsome build` but not `gridsome develop`.

In develop mode the following scss:

```
<style lang="scss">
.slideshow {
  @screen lg {
    width: 100vw;
    height: 58vw;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 0;
    overflow: hidden;
    list-style: none;
  }
  padding: 0;
  margin: 0;
}
</style>
```

 Is output in the browser as this:

```
<style type="text/css">
.slideshow {
  padding: 0;
  margin: 0;
}
@screen lg {
.slideshow {
    width: 100vw;
    height: 58vw;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 0;
    overflow: hidden;
    list-style: none;
}
}
</style>
```

Other nested scss works and outputs fine. Any ideas?

**Comment by brandonpittman** [comment]
Does it work if you put the screen directive on the outside of the class def?

**Comment by tanc** [comment]
Unfortunately not:
```
<style lang="scss">
.slideshow {
  padding: 0;
  margin: 0;
}
@screen lg {
  .slideshow {
    width: 100vw;
    height: 58vw;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 0;
    overflow: hidden;
    list-style: none;
  }
}
</style>
```

```
<style>
.slideshow {
  padding: 0;
  margin: 0;
}
@screen lg {
.slideshow {
    width: 100vw;
    height: 58vw;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 0;
    overflow: hidden;
    list-style: none;
}
}
</style>
```

**Comment by tanc** [comment]
The same thing is happening with the `@apply` function:

```
h1, h2, h3 {
@apply font-heading;
}
```

**Comment by tanc** [comment]
I just set up a fresh gridsome site to test and try to replicate but it seems to be working fine there. So it must be a clash with some config I have on the non-working site. In my `gridsome.config.js` I have this section:

```
chainWebpack: config => {
  const oneOfsMap = config.module.rule('scss').oneOfs.store
  oneOfsMap.forEach(item => {
    item
      .use('sass-resources-loader')
      .loader('sass-resources-loader')
      .options({
        resources: [
          './src/assets/scss/_linear-interpolation.scss',
          './src/assets/scss/_map-sort.scss',
          './src/assets/scss/_list-sort.scss',
          './src/assets/scss/_list-remove.scss',
          './src/assets/scss/_poly-fluid-sizing.scss',
          './src/assets/scss/_ribbon.scss',
        ]
      })
      .end()
  })
}
```

I wonder if that is causing a problem? I'm not knowledgeable enough with Webpack to understand how chaining works

**Comment by brandonpittman** [comment]
Not sure, but seems like a Sass issue. The Tailwind docs recommend against wandering into pre-processors. 

https://tailwindcss.com/docs/using-with-preprocessors/#app

I also agree they are antithetical to Tailwind, so even if it could be made to work around any Sass issues, I don’t think I’d support it.
